### ISSUE TITLE
docker compose example

### ISSUE THREAD

**Issue by Heggeg** [bluet/proxybroker2#107]
Could you create please some docker-compose examples?

**Comment by ziloka** [comment]
Heres what it would look like
```
version: "3.9"  # optional since v1.27.0
services:
  proxybroker2:
    image: bluet/proxybroker2
    command: serve --host 127.0.0.1 --port 8888 --types HTTP HTTPS --lvl High --min-queue 5
    ports:
      - 8888
```

I'm not really sure what else you would use as a service.
